name: Pytest

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pytest 7.1.3
        run: pip install pytest==7.1.3
      - name: Install binheap package
        run: python -m pip install .
      - name: Run pytest
        run: pytest tests/ -vv